### ISSUE TITLE
v0.7.1 β will not open on macos 10.15.7

### ISSUE THREAD

**Issue by BillyJoeJimBob** [synappser/FinderFix#11] opened 2023-01-13 10:22 UTC
**Describe the bug**
FinderFix v0.7.1 β is running as expected on my iMac (macOS 13 Ventura), however it will not open at all on my MBP running macOS 10.15.7 (Catalina), reopening of #6

**To Reproduce**
1) Click on FinderFix 0.7.1 in macOS 10.15.7. 
2) Nothing happens.
3) Log shows a crash.
4) After several failed attempts to open the app, I  then manually added FinderFix to Security & Privacy: 'Accessibility' and 'Full Disk Access' and clicked on FinderFix again, nothing happens.

**Expected behavior**
FinderFix application starts.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - CPU: 2.3 GHz Quad-Core Intel Core i7 3615QM Ivy Bridge
 - MacBookPro10,1 (Retina Mid 2012)
 - System Locale English - US
 - Version v0.7.1b

**Additional context**
-Log: 

[FinderFix_2023-01-13.txt](https://github.com/synappser/FinderFix/files/10410470/FinderFix_2023-01-13.txt)

If there is a better way to submit the log, please let me know, when i try to just paste the text here, the formatting is a mess.  And thank you very much for making this app.  I've been using a combination of FinderMinder + a script called FinderSize for years, and it's the least bad option I've been able to find.  I just don't know why apple doesn't at least offer an option to pin Finder at a set size/location like most apps.

**Comment by synappser** [comment] 2023-01-13 10:48
@BillyJoeJimBob, Thank you for reporting this issue. Your crash log is perfectly usable. I am intrigued by this call to RawCamera here:

`0x7fff2cfb9000 -     0x7fff2d206ff8  com.apple.RawCamera.bundle (9.02.0 - 1350.30) <5337D338-FB27-3B70-91C8-096357BEFAC2> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera`

I will try to symbolicate it and I hope it will help me identify the origin of  this crash.

**Comment by BillyJoeJimBob** [comment] 2023-01-14 03:00
Thanks.  I've been using some old scripts dating back to at least Leopard 10.5, but they still work to resize the finder in Catalina.  https://web.archive.org/web/20150425163353/http://www.macupdate.com/app/mac/30277/finder-size-position-scripts

**Comment by synappser** [comment] 2023-01-15 14:37
@BillyJoeJimBob, Sorry symbolication is leading me nowhere. I also was not able to reproduce the crash on a similar macOS version (10.15.7) running in a virtual environment. I'm closing this for now, hoping the next release will fare better on your system.

**Closed by synappser** 2023-01-15 14:37 UTC
Labels: cannot reproduce
